---
date: "2021-06-30T00:00:00+01:00"
draft: false
menu:
  log_adm:
    parent: Estudos autônomos
    weight: 6
title: 2. KPI e desempenho logístico
editor_options: 
  markdown: 
    wrap: 70
output: 
  blogdown::html_page:
    toc: true
type: docs
weight: 7
---

Leia os artigos: 

- [Tecnologia da Informação aplicada à Logística by Paulo R. Bertaglia](https://www.dropbox.com/s/gtqxne83suoownb/ti2013.pdf?dl=0)

- [Logística + Tecnologia: na prática a teoria é outra](https://www.dropbox.com/s/4szfw6offjrpepo/ti_pratica.pdf?dl=0) 

- [Supply Chain 4.0 - a reconfiguração das cadeias de suprimentos](https://www.dropbox.com/s/iverdlbcq7xu2ou/2020_varejo.pdf?dl=0)

Responda as questões a seguir de maneira colaborativa em seu grupo de trabalho e submeta pela respectiva tarefa do SIGAA.

O prazo de entrega desta atividade pelo SIGAA é **06/12**. 

> Não se esqueçam de incluir o nome dos membros do grupo na postagem!

1. O que são e qual a importância de KPIs para a gestão da cadeia de suprimentos?

2. Você trabalha na empresa Entrega Rápida que atua no mercado como operador logístico para e-commerce. Você tem três clientes majoritários, a saber: (i) portoriquenhos.com; (ii) submarinonuclear.com; e (iii) purchasetime.com. Para estes clientes você, como analista de transporte, deve gerenciar a cadeia de suprimentos e, em especial, a distribuição no último quilômetro a fim de obter a melhor relação custo/benefício da operação (os menores custos possíveis com o maior nível de serviço, adequado às expectativas dos varejistas e dos consumidores finais). Entretanto, você trabalhará sozinho no controle da entrega de último quilômetro para os clientes desses três varejistas, e há escassez de mão de obra alocada para esse processo gerencial.

Assim, será possível escolher apenas três indicadores de desempenho (KPI) para todas as classes de atributos a serem monitorados:

a. desempenho no atendimento ao cliente
b. desempenho na gestão de estoques
c. produtividade do armazém
d. desempenho em transportes

Destaca-se a importância do trade-off (custo operacional x nível de serviço). Você poderá escolher, dentre aqueles indicadores apresentados nos documentos e pesquisados em conteúdo na internet, três indicadores de forma a completar a visão gerencial do seu processo. Quais são esses três indicadores e por que você os escolheu? Lembre-se que são apenas três indicadores para todas as classes de atributos a serem monitorados.

3. Quais as contribuições essenciais das TICs para a gestão da cadeia de suprimentos? Existem aspectos negativos da implementação de TI quando o objetivo da gestão da cadeia de suprimentos está centrado no trade-off entre responsividade e eficiência? Há diferenças do papel das TICs quando os conceitos de sustentabilidade e resiliência são considerados como objetivos estratégicos da SCM?

4. Vocês acreditam que tecnologias como a Impressão 3D podem viabilizar uma gestão da cadeia de suprimentos mais responsiva e eficiente? Explique o seu ponto de vista. 

