---
date: "2021-10-15T00:00:00+01:00"
draft: false
menu:
  intro_r:
    parent: 1 - Primeiros passos
    weight: 15
title: Criando sua conta no Github
editor_options: 
  markdown: 
    wrap: 70
output: 
  blogdown::html_page:
    toc: true
type: docs
weight: 15
---


## Definições

`GitHub` é o lugar onde você pode armazenar todas estas versões de seu trabalho. Outros desenvolvedores podem ver, fazer uma cópia, alterar sua cópia e fazer sugestões sobre seu trabalho.

## Vocabulário básico para uso do `GitHub`:

- `Repositório`: Quando você faz uma conta no `Github`, a primeira coisa que você vai querer fazer é criar um repositório (ou repo). Este é o lugar para armazenar todos os seus arquivos para um determinado projeto.

- `Fork:` Digamos que você realmente gosta do projeto de outra pessoa no `GitHub` e você gostaria de fazer uma cópia dele em sua conta para ajustar como você quiser? Bem, esse processo é chamado de `forking`. Para fazer isso, encontre um reporte que você gosta e clique no botão `fork` no canto direito.

- `Branch`: Esta é uma "versão paralela" de um projeto que você pode ajustar sem impactar o projeto original.

- `Remote`: A cópia de seus arquivos que residem no `GitHub.com`. É o endereço "destinatário" do seu projeto na plataforma online.

- `Local:` A cópia de seus arquivos que residem em seu computador. É um espelho do repositório remoto.

- `Commit`: Uma alteração em um arquivo, geralmente apresentada com uma mensagem sua para indicar o que foi alterado.

- `Push`: Uma vez que você realize mudanças em seus arquivos locais, você quer enviá-las (ou empurrá-las) para seu repositório remoto, tornando-as disponíveis para outros.

- `Pull`: Se várias pessoas estiverem trabalhando em seu repositório remoto, elas podem ter feito uma mudança que não está refletida em sua versão local. Você pode `puxar` a versão mais nova para o seu computador para trabalhar nela.

## Como operacionalizar?

Vá ao site do [Github.com](Github.com) e crie uma conta gratuita. Faça seu login. 
Na página dos seus repositórios, crie um repositório e faça uso desse espaço para controlar as versões de projetos diversos. 

Para quem, como eu, não curte muito ter que lembrar comandos em linha o tempo todo, existem aplicativos GUI que permitem a gestão dos repositórios `local` e `remoto`. O próprio `Github` tem um aplicativo desktop para gestão. Entretanto, por achar mais simples (cada um vai se sentir mais confortável com uma interface), estou usando o [GitKraken](https://www.gitkraken.com/). 

Ainda tenho que me acostumar a utilizar o `RStudio` para gerenciar versão no `Github`. Sim, é possível. Mas também estão disponíveis os aplicativos `desktop` como `GitHub Desktop` e o `GitKraken`. 

<iframe width="1218" height="645" src="https://www.youtube.com/embed/DL6BkIFxL9Q?list=PLqDTVtdD-5aOczVvI_Ga_1qKFtYof5XGB" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

----

Créditos: https://amber.rbind.io/2016/12/19/website/

----

> BÔNUS [Happy Git with R](https://happygitwithr.com/)


