---
date: "2020-12-275T00:00:00+01:00"
draft: false
menu:
  log:
    parent: Estudos autônomos
    weight: 10
title: Gestão de estoques e armazenagem
editor_options: 
  markdown: 
    wrap: 70
output: 
  blogdown::html_page:
    toc: true
type: docs
weight: 10
---

O PRAZO DE ENTREGA DESTA ATIVIDADE PELO SIGAA É: **06/04**


> Não se esqueçam de incluir o nome dos membros do grupo na postagem!

Leia os artigos:

[Planejamento dos Recursos da Distribuição](https://github.com/retaoliveira/relements/raw/main/texto/estoque1.pdf)

[Gerenciamento de Armazéns](https://github.com/retaoliveira/relements/raw/main/texto/ama1.pdf)

[Dicas para aumentar a produtividade e a eficiência na armazenagem de cargas](https://github.com/retaoliveira/relements/raw/main/texto/ama2.pdf)

e responda as perguntas que seguem na atividade no Sigaa referente ao representante do grupo.

1. Como você pensa a proposta de planejamento de estoques apresentada no primeiro artigo no contexto da 4a revolução industrial e do pós-pandemia para a última milha (ou último quilômetro) do setor varejista? Faça a sugestão de algum elemento que pode ser inviável considerar no planejamento nesse contexto e explique por que. 

2. Qual a diferença entre gestão de estoques e armazenagem? Qual função é mais relevante para garantia de responsividade e eficiência na gestão da cadeia de suprimentos?

3. Faça uma pesquisa rápida na internet sobre automação de armazéns e discuta as principais diferenças entre o modelo tradicional de operações de armazenagem e o processo automatizado. 


