---
date: "2019-05-05T00:00:00+01:00"
draft: false
menu:
  dados_pos:
    parent: Projetos
    weight: 14
title: Projeto 2
toc: true
type: docs
weight: 14
---

## Pré-requisitos

Conhecimento nos pacotes do `tidyverse` (`ggplot`, `readr`, `dplyr`)

## Atividades para consolidação do Projeto 02:

Esta atividade tem valor de 10 pontos e, apesar de estar relacionada ao projeto integrador, é avaliada de maneira separada. O prazo para entrega desta atividade é dia **22/03/2021**. 

### Utilizar o documento de comunicação (relatório, apresentação ou outro de sua escolha) em `RMarkdown` gerado para o **Projeto 1**. Faremos, nesta etapa, a limpeza dos dados e a organização do banco de dados com os atributos que serão analisados no **Projeto Integrador**.

#### 1. Abrir arquivo `RMarkdown` (.Rmd)

#### 2. Editar o cabeçalho YAML no topo do documento, incluindo:
- Data
- Título que represente o conteúdo do relatório
- Autores do grupo

#### 3. Mantenha o conteúdo (ou aprimore) apresentado no documento do **Projeto 1**. 

#### 4. Carregue os dados que serão necessários para análise do problema descrito. 

Gere um objeto para cada data frame e inclua no seu .Rmd a apresentação preliminar do dado (`head()`) e alguma função de exploração do dados, como `str()`, `names()`, `nrow()`... 

#### 5. Faça representações preliminares dos dados.

Gere algumas representações dos dados que permitam entender as medidas de tendência central (média, mediana) em relação à dispersão dos dados (boxplot, histograma, barras). Lembre-se que tipos diferentes de gráficos no `ggplot2` devem ser gerados para tipos diferentes de dados. 

Trabalhe nessas representações relacionando atributos importantes para caracterização do processo em investigação. 

#### 6. Faça limpezas necessárias para que os dados fiquem **tidy** .

Lembre-se que um dado **tidy** deve considerar que:
- Cada variável forma uma coluna.
- Cada observação forma uma linha.
- Livre de linhas/colunas duplicadas.
- Livre de erros de ortografia
- Relevante (por exemplo, livre de caracteres especiais)
- O tipo de dados apropriado para análise
- Livre de outliers (ou só contém outliers que tenham sido identificados/entendidos)

Utilize as funções disponíveis em `dplyr`:

- `select`: seleção de colunas pelo nome
- `arrange`: reorganização das colunas
- `slice`: seleção de linhas pelo index(es)
- `filter`: seleção de linhas segundo algum critério
- `distinct`: aplica um filtro para que não haja colunas duplicadas
- `mutate`: adição de novas variáveis
- `summarise`: redução de variáveis a valores
- `group_by`: operações em agrupamentos
- ... (many more)

Represente (`head()`) os dados após a limpeza e explique o que foi necessário fazer para gerar dados **tidy**.


## Rubrica de avaliação

Embora a presença nos encontros síncronos não seja explicitamente acompanhada, a participação neste curso conta para sua nota. A seguir, são apresentados os critérios considerados para a avaliação do projeto 1 que são úteis para nortear o desenvolvimento do trabalho. 

### Relatório RMarkdown

|Item|Proporção da nota
|----|-----------------
|Sintaxe do código |20%
|HTML e Rmd apresentados|0,5 pontos
|YAML contém título, autor e data|0,5 pontos
|O arquivo foi nomeado conforme diretrizes|0,5 pontos
|A gramática e a ortografia são excelentes - sem erros de ortografia|0,5 pontos

|Item|Proporção da nota
|----|-----------------
|Dados|80%
|Dados e suas estatísticas descritivas representados de maneira clara e relevante|4 pontos 	 
|Limpeza dos dados realizada de maneira assertiva e completa |4 pontos
